#!/usr/bin/env python3
"""Translate the Swift source tree into a reviewable Dart starting point.

This is intentionally a syntax translator, not a compiler: SwiftUI, SwiftData,
property wrappers, and Apple frameworks need platform-specific Flutter designs.
Unsupported constructs are kept in comments so a whole project can be
translated in one pass without silently losing behavior.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


DEFAULT_ROOTS = ("Piru", "Shared", "PiruWidget", "PiruLiveActivityExtension")
DEFAULT_EXCLUDES = ("Tests", "Preview Content")


def _generic_type(value: str) -> str:
    value = re.sub(r"\bAny\b", "dynamic", value)
    value = re.sub(r"\bAnyObject\b", "Object", value)
    value = re.sub(r"\bString\b", "String", value)
    value = re.sub(r"\bInt64?\b", "int", value)
    value = re.sub(r"\bUInt64?\b", "int", value)
    value = re.sub(r"\bDouble\b|\bFloat\b", "double", value)
    value = re.sub(r"\bBool\b", "bool", value)
    value = re.sub(r"\bDate\b", "DateTime", value)
    value = re.sub(r"\bUUID\b", "String", value)
    value = re.sub(r"\[([^:\]]+):\s*([^\]]+)\]", r"Map<\1, \2>", value)
    value = re.sub(r"\[([^\]]+)\]", r"List<\1>", value)
    return value


def _translate_line(line: str) -> str:
    indent = line[: len(line) - len(line.lstrip())]
    text = line.strip()
    if not text:
        return ""
    has_optional_binding = bool(re.search(r"\b(?:if|guard)\s+let\b", text))
    if text.startswith("import "):
        return f"{indent}// {text} (Swift framework import; add the Flutter equivalent)"
    if text.startswith("@"):
        return f"{indent}// {text} (Swift annotation requires a Flutter design)"
    if text.startswith(("///", "//")):
        return line

    text = re.sub(r"^(public|private|internal|fileprivate|open|final)\s+", "", text)
    text = re.sub(r"^(nonisolated|override|static)\s+", "", text)
    text = re.sub(r"^(struct|class)\s+(\w+)", r"class \2", text)
    text = re.sub(r"\benum\s+(\w+)", r"enum \1", text)
    text = re.sub(r"\b(let|var)\s+(\w+)\s*:", r"final \2:", text)
    text = re.sub(r"\b(let|var)\s+(\w+)\s*=", r"final \2 =", text)
    text = text.replace("nil", "null")
    text = text.replace("true", "true").replace("false", "false")
    text = text.replace("&&", "&&").replace("||", "||")

    # Swift's trailing return syntax is the most common mechanically
    # translatable function form.
    text = re.sub(
        r"func\s+(\w+)\s*\(([^)]*)\)\s*->\s*([^{]+)\s*\{?",
        lambda m: f"{_generic_type(m.group(3).strip())} {m.group(1)}({m.group(2)}) {{",
        text,
    )
    text = re.sub(r"\bfunc\s+(\w+)\s*\(([^)]*)\)\s*\{?", r"void \1(\2) {", text)
    text = re.sub(r"\bthrows\b|\basync\b|\bawait\b", "", text)
    text = re.sub(r"\bguard\b|\bwhere\b", "/* unsupported Swift control flow */", text)
    text = re.sub(r"\belse\s+if\b", "else if", text)
    text = re.sub(r"\b(String|Int64?|UInt64?|Double|Float|Bool|Date|UUID|AnyObject|Any)\b", lambda m: _generic_type(m.group(1)), text)
    text = re.sub(r"\b([A-Za-z_]\w*)\?\b", r"\1?", text)
    text = re.sub(r"\b([A-Za-z_]\w*)\.now\b", r"DateTime.now()", text)
    text = re.sub(r"\b([A-Za-z_]\w*)\.lowercased\(\)", r"\1.toLowerCase()", text)
    text = re.sub(r"\b([A-Za-z_]\w*)\.uppercased\(\)", r"\1.toUpperCase()", text)
    text = text.replace("String(localized:", "/* localized */ String(")
    text = text.replace("...", "/* range */")

    if text.startswith("switch "):
        text = "// TODO Flutter: replace Swift switch with Dart switch\n" + text
    if has_optional_binding:
        text = "// TODO Flutter: rewrite Swift optional binding: " + text
    return indent + text


def translate_source(source: str, relative_path: str) -> str:
    header = [
        "// GENERATED by tools/swift_to_flutter.py.",
        f"// Source: {relative_path}",
        "// Review TODO markers before using this in a Flutter target.",
        "",
    ]
    return "\n".join(header + [_translate_line(line) for line in source.splitlines()]) + "\n"


def swift_files(roots: list[Path], excludes: tuple[str, ...]) -> list[Path]:
    files: list[Path] = []
    for root in roots:
        if root.is_file() and root.suffix == ".swift":
            files.append(root)
        elif root.is_dir():
            files.extend(path for path in root.rglob("*.swift") if not any(part in excludes for part in path.parts))
    return sorted(set(files))


def translate_tree(repo: Path, output: Path, roots: list[str], excludes: tuple[str, ...]) -> int:
    files = swift_files([repo / root for root in roots], excludes)
    for source_path in files:
        relative = source_path.relative_to(repo)
        target = output / relative.with_suffix(".dart")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(translate_source(source_path.read_text(), str(relative)), encoding="utf-8")
    return len(files)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=Path.cwd(), help="Swift repository root")
    parser.add_argument("--output", type=Path, required=True, help="Directory for generated Dart files")
    parser.add_argument("--root", action="append", dest="roots", help="Source root (repeatable)")
    parser.add_argument("--exclude", action="append", default=[], help="Directory name to skip")
    args = parser.parse_args()
    roots = args.roots or list(DEFAULT_ROOTS)
    excludes = tuple(DEFAULT_EXCLUDES) + tuple(args.exclude)
    count = translate_tree(args.input.resolve(), args.output.resolve(), roots, excludes)
    print(f"Translated {count} Swift files to {args.output.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
